server:
  port: 8080

spring:
  application:
    name: call
---

spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: call
#<<< EDA / Topic Name
          destination: taxisvc
#>>> EDA / Topic Name
          contentType: application/json
        event-out:
#<<< EDA / Topic Name
          destination: taxisvc
#>>> EDA / Topic Name
          contentType: application/json

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 3000  # 연결 timeout
        readTimeout: 610      # 응답 대기 timeout
        retryer:
          period: 2000        # 재시도 주기 
          maxPeriod: 5000     # 최대 재시도 주기 
          maxAttempts: 2      # 최대 재시도 횟수 
hystrix:
  command:
    # 전역설정
    default:
      execution.isolation.thread.timeoutInMilliseconds: 610 # 읽기 타임아웃 (밀리초 단위)
      
# logging:
#   level:
#     org.hibernate.type: trace
#     org.springframework.cloud: debug
logging:
  level:
    root: ${ORDER_LOG_LEVEL}
    org:
      hibernate:
        SQL: ${ORDER_LOG_LEVEL}
      springframework:
        cloud: ${ORDER_LOG_LEVEL}

api:
  url: 
    payment: localhost:8083 
    

server:
  port: 8082

---

spring:
  profiles: docker
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: call
          destination: taxisvc
          contentType: application/json
        event-out:
          destination: taxisvc
          contentType: application/json

api:
  url: 
    payment: payment:8080 

logging:
  level:
    root: ${ORDER_LOG_LEVEL}
    org:
      hibernate:
        SQL: ${ORDER_LOG_LEVEL}
      springframework:
        cloud: ${ORDER_LOG_LEVEL}
    

